title: "Data Science Portfolio – Esmaeil Pourjavad"
description: "Showcasing professional and self-driven projects in Data Science, MLOps, and AI"
theme: jekyll-theme-cayman
url: "https://returnkeys.github.io"
baseurl: "/data-science-portfolio"
